/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Testx */

#ifndef _Included_Testx
#define _Included_Testx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Testx
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Testx_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
