/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_srimadhav_Simulator */

#ifndef _Included_com_srimadhav_Simulator
#define _Included_com_srimadhav_Simulator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_srimadhav_Simulator
 * Method:    run
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_srimadhav_Simulator_run
  (JNIEnv *, jclass, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
